version: '3'

services:
  todoback:
    build: todo-app/back-end/
    restart: always
    ports:
      - 3001:3001
  todofront:
    depends_on:
      - todoback
    build: todo-app/front-end/
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
  todotests:
    depends_on:
      - todoback
      - todofront
    build: todo-app/tests/
    restart: always
    environment:
      - FRONT_HOST=todofront